Update pipelines.adoc
aadeshpa/draft-guide-working-with-pipelines pull request #1
Opened 2019-11-14 21:45 UTC by aadeshpa

updated the document with the configmap and secret for setting the custom collection registry url

2019-12-05 15:45 UTC, kvijai82 commented on pipelines.adoc
> +By default the pipelines assume you are pulling the collection from `kabanero` so it looks for the collection image in dockerhub repository. If you want to use your container registry URL where you h
I would reword it to maybe something like this.  It's good from most part, but the statement it pulls from kabanero is not fully true.  It's more that it looks in docker hub.

By default, the pipelines pull the collection images for docker hub.  If you are publishing your collection images to any other repository, follow the instructions below to configure the custom repository that the pipelines should pull the collection images from.

2019-12-05 15:46 UTC, kvijai82 commented on pipelines.adoc
> +For internal openshift registry you need to only setup above `collection-image-registry-map.yaml` with the internal registry url.
Also maybe add that the service account should let the pipelines pull from the registry without needing to configure a secret.

2019-12-05 16:22 UTC, kvijai82 approved these changes

2019-12-05 18:42 UTC, dmuelle requested changes
changes requested below. This will probably require more editing once it goes back to the main repo but I can edit there and send a PR for your approval. Let me know if you have any questions or if I've misunderstood the intention of anything. Thanks

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +== Execute pipelines manually from the command line for your custom built Collections
**change**
Execute pipelines manually from the command line for your custom built Collections
**to**
Run pipelines from the command line for your custom built collections

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +If you have your own custom build collection image and want to run any pipelines against it instead of out of box kabanero collections, then you need to follow below steps as per the required scenari
**change**
If you have your own custom build collection image and want to run any pipelines against it instead of out of box kabanero collections, then you need to follow below steps as per the required scenarios.
**to**
The following steps explain how to run pipelines against custom built collection images instead of the provided Kabanero collections.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +=== Setup of container registry url for the custom Collection image
**change**
Setup of container registry url for the custom Collection image
**to**
Set up a container registry URL for the custom collection image

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +By default, the pipelines pull the collection images for docker hub. If you are publishing your collection images to any other repository, follow the instructions below to configure the custom reposi
**change**
By default, the pipelines pull the collection images for docker hub. If you are publishing your collection images to any other repository, follow the instructions below to configure the custom repository that the pipelines should pull the collection images from.

**to**
By default, pipelines pull the collection images for Docker hub. If you are publishing your collection images to any other repository, use the following process to configure the custom repository from which your pipelines pull the collection images.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. After you have cloned kabanero-pipelines repository find the configmap template file `collection-image-registry-map.yaml` and add your container registry URL in it for the key `default-collection-i
**change**
After you have cloned kabanero-pipelines repository find the configmap template file `collection-image-registry-map.yaml` and add your container registry URL in it for the key `default-collection-image-registry-url` 

**to**
After you clone the kabanero-pipelines repository, find the `collection-image-registry-map.yaml` configmap template file.  Add your container registry URL to this file in place of the `default-collection-image-registry-url` statement.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. Apply the above configmap file which will set your container registry.
**change**
 cd kabanero-pipelines/pipelines/common/
 vi collection-image-registry-map.yaml

. Apply the above configmap file which will set your container registry.

**to**
. Apply the following configmap file, which will set your container registry. 

cd kabanero-pipelines/pipelines/common/
 vi collection-image-registry-map.yaml

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> + oc apply -f collection-image-registry-map.yaml
what is the significance of this command? it's not explained

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +==== For Collection image stored in container registry with internal route url on the OCP cluster
**change**
For Collection image stored in container registry with internal route url on the OCP cluster
**to**
Set up a container registry URL for a custom collection image that is stored in a container registry with an internal route URL on the OCP cluster

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +NOTE : The service account should let the pipelines pull from the internal registry without needing to configure a secret.
**change**
NOTE : The service account should let the pipelines pull from the internal registry without needing to configure a secret.

**to**
In this case, the service account that is associated with the pipelines must be configured to allow the pipelines pull from the internal registry without configuring a secret.

is there somewhere we can point to for information about service accounts? ie "For more information, see x"

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +For internal openshift registry you need to only setup above `collection-image-registry-map.yaml` with the internal registry url.
**change**
For internal openshift registry you need to only setup above `collection-image-registry-map.yaml` with the internal registry url.
**to**
For an internal OpenShift registry, set up the `collection-image-registry-map.yaml` file with the internal registry URL.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +==== For Collection image stored in container registry with external route url
**Change**
For Collection image stored in container registry with external route url
**to**
Set up a container registry URL for a custom collection image that is stored in a container registry with an external route URL

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +For collection image with external container registry route url you need to setup a kubernetes secret in addition to above configured configmap as per below steps.
what is the purpose of the kubernetes secret? it's not mentioned again.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. Find the template file `default-collection-image-registry-secret.yaml` in cloned kabanero-pipelines repo and update it with the username and token password for the container registry url you specif
**change**
. Find the template file `default-collection-image-registry-secret.yaml` in cloned kabanero-pipelines repo and update it with the username and token password for the container registry url you specified above.
**to**
. First, update the `collection-image-registry-map.yaml` file with your container registry file, as described in step 1 of `Set up a container registry URL for the custom collection image`.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> + cd kabanero-pipelines/pipelines/common
is this command necessary? should step one here be "Go to the `kabanero-pipelines/pipelines/common` directory?

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. You need to first create `base64` format of the username and password for the container registry url.
**change**
You need to first create `base64` format of the username and password for the container registry url.
**to**
Create a Base64 format version of the user name and password for the external route container registry url.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. Update the file `default-collection-image-registry-secret.yaml` with `base64` format from above step output.
**change**
Update the file `default-collection-image-registry-secret.yaml` with `base64` format from above step output.
**to**
Update the `default-collection-image-registry-secret.yaml` file with the Base64 formatted user name and password.

2019-12-05 18:42 UTC, dmuelle commented on pipelines.adoc
> +. Finally run the pipeline as shown in above section.
**change**
Finally run the pipeline as shown in above section.
**to**
You can now run the pipeline by following the steps in the preceding `Run pipelines from the command line for your custom built collections` section.

2019-12-09 14:55 UTC, kvijai82 approved these changes

2019-12-09 14:56 UTC, dmuelle approved these changes
approving here to make ID edits in main repo

2020-01-02 20:35 UTC, merged